# Enhanced Thesis Generator Configuration
# ======================================

# AI Configuration
ai:
  provider: openai
  model: gpt-4
  deterministic: true
  temperature: 0.0
  top_p: 1.0
  max_tokens: 4000

# Output Configuration
output:
  formats:
    - markdown
    - latex
    - html
  directory: thesis_output
  include_cache: true
  save_intermediate: true

# Processing Configuration
processing:
  use_cache: true
  cache_version: v1.1
  human_checkpoints: true
  theme_count: 5
  max_gaps: 5
  max_research_questions: 4

# Template Configuration
templates:
  directory: templates/thesis
  custom_filters: true
  
# Quality Settings
quality:
  min_theme_length: 200
  min_gap_description: 150
  citation_style: apa
  academic_rigor: phd

# Performance Settings
performance:
  parallel_processing: false
  max_retries: 3
  timeout_seconds: 120
