# Eunice Research Platform - Version 0.3 Microservices Architecture
# Root-level orchestration following the Version 0.3 design document

services:
  # Core Services

  # 1. API Gateway Service (Port 8001)
  api-gateway:
    build: ./services/api-gateway
    container_name: eunice-api-gateway
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - MCP_SERVER_HOST=mcp-server
      - MCP_SERVER_PORT=9000
      - DATABASE_SERVICE_URL=http://database-service:8011
      - LOG_LEVEL=INFO
    networks:
      - eunice-microservices
    depends_on:
      - mcp-server
      - database-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 2. Enhanced MCP Server Service (Port 9000)
  mcp-server:
    build: ./services/mcp-server
    container_name: eunice-mcp-server
    ports:
      - "9000:9000"
    environment:
      - LOG_LEVEL=INFO
      - PORT=9000
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/eunice
    networks:
      - eunice-microservices
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "validate.py"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 3. AI Service (MCP Client)
  ai-service:
    build: ./services/ai-service
    container_name: eunice-ai-service
    environment:
      - MCP_SERVER_URL=ws://mcp-server:9000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - LOG_LEVEL=INFO
    networks:
      - eunice-microservices
    depends_on:
      - mcp-server
    restart: unless-stopped

  # 4. Planning Agent (Port 8007)
  planning-agent:
    build: ./agents/planning
    container_name: eunice-planning-agent
    ports:
      - "8007:8007"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8007
      - MCP_SERVER_URL=ws://mcp-server:9000
      - AGENT_TYPE=planning
      - LOG_LEVEL=INFO
    networks:
      - eunice-microservices
    depends_on:
      - mcp-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 8. Database Service (Port 8011)
  database-service:
    build: ./services/database
    container_name: eunice-database-service
    ports:
      - "8011:8011"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/eunice
      - LOG_LEVEL=INFO
    networks:
      - eunice-microservices
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8011/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Supporting Infrastructure

  # Redis (Message Broker & Cache)
  redis:
    image: redis:7-alpine
    container_name: eunice-redis
    ports:
      - "6380:6379" # Use different external port to avoid conflict
    networks:
      - eunice-microservices
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: eunice-postgres
    ports:
      - "5433:5432" # Use different external port to avoid conflict
    environment:
      - POSTGRES_DB=eunice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eunice-microservices
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development Tools (Optional)

  # Nginx (Load Balancer/Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: eunice-nginx
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - eunice-microservices
    depends_on:
      - api-gateway
    restart: unless-stopped
    profiles:
      - production

# Networks
networks:
  eunice-microservices:
    driver: bridge
    name: eunice-microservices
    labels:
      - "com.eunice.network=microservices"
      - "com.eunice.version=v0.3"

# Volumes
volumes:
  postgres-data:
    name: eunice-postgres-data
    labels:
      - "com.eunice.volume=database"
