# Development Override Configuration
# Use with: docker compose -f docker-compose.secure.yml -f docker-compose.dev.yml up

services:
  api-gateway:
    build:
      context: ./services/api-gateway
      target: development
    command: ["tini", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
    volumes:
      # Mount source code for development
      - ./services/api-gateway/src:/app/src:ro
      - ./services/api-gateway/native_database_client.py:/app/native_database_client.py:ro
      - ./services/api-gateway/main.py:/app/main.py:ro
      - ./services/api-gateway/config.py:/app/config.py:ro
      - ./services/api-gateway/mcp_client.py:/app/mcp_client.py:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []

  # Override other services for development if needed
  planning-agent:
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true

  ai-service:
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
