# Development Override Configuration
# Use with: docker compose -f docker-compose.secure.yml -f docker-compose.dev.yml up

services:
  api-gateway:
    build:
      context: ./api-gateway
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
    volumes:
      # Mount source code for development
      - ./api-gateway/src:/app/src:ro
      - ./api-gateway/native_database_client.py:/app/native_database_client.py:ro
      - ./api-gateway/main.py:/app/main.py:ro
      - ./api-gateway/config.py:/app/config.py:ro
      - ./api-gateway/mcp_client.py:/app/mcp_client.py:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []

  # Network Agent development configuration
  network-agent:
    build:
      context: ./agents/network
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
      - WATCHFILES_FORCE_POLLING=1
    volumes:
      # Mount source code for development
      - ./agents/network/src:/app/src:ro
      - ./agents/network/config:/app/config:ro
      - ./agents/network/start-dev.sh:/app/start-dev.sh:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []

  # Research Manager development configuration
  research-manager:
    build:
      context: ./research-manager
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
      - WATCHFILES_FORCE_POLLING=1
    volumes:
      # Mount source code for development
      - ./research-manager/src:/app/src:ro
      - ./research-manager/config:/app/config:ro
      - ./research-manager/start-dev.sh:/app/start-dev.sh:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []
