# Development Override Configuration
# Use with: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  api-gateway:
    build:
      context: ./services/api-gateway
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
    volumes:
      # Mount source code for development
      - ./services/api-gateway/src:/app/src:ro
      - ./services/api-gateway/native_database_client.py:/app/native_database_client.py:ro
      - ./services/api-gateway/main.py:/app/main.py:ro
      - ./services/api-gateway/config.py:/app/config.py:ro
      - ./services/api-gateway/mcp_client.py:/app/mcp_client.py:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []

  # MCP Server development configuration
  mcp-server:
    build:
      context: ./services/mcp-server
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
      - WATCHFILES_FORCE_POLLING=1
    volumes:
      # Mount source code for development
      - ./services/mcp-server/mcp_server.py:/app/mcp_server.py:ro
      - ./services/mcp-server/config.py:/app/config.py:ro
      - ./services/mcp-server/start-dev.sh:/app/start-dev.sh:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []

  # Research Manager Agent development configuration
  research-manager-agent:
    build:
      context: ./agents/research-manager
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
      - WATCHFILES_FORCE_POLLING=1
    volumes:
      # Mount source code for development
      - ./agents/research-manager/src:/app/src:ro
      - ./agents/research-manager/config:/app/config:ro
      - ./agents/research-manager/start-dev.sh:/app/start-dev.sh:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []

  # Database Service development configuration
  database-service:
    build:
      context: ./services/database
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
      - WATCHFILES_FORCE_POLLING=1
      - HEALTH_CHECK_INTERVAL=10
      - MAINTENANCE_INTERVAL=1800
    volumes:
      # Mount source code for development
      - ./services/database/database_service.py:/app/database_service.py:ro
      - ./services/database/database_tools.py:/app/database_tools.py:ro
      - ./services/database/mcp_client.py:/app/mcp_client.py:ro
      - ./services/database/start-dev.sh:/app/start-dev.sh:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []

  # Memory Service development configuration
  memory-service:
    build:
      context: ./services/memory
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
      - WATCHFILES_FORCE_POLLING=1
      - MEMORY_DB_PATH=/tmp/memory_dev.db
      - HEALTH_CHECK_INTERVAL=10
    volumes:
      # Mount source code for development
      - ./services/memory/src:/app/src:ro
      - ./services/memory/start-dev.sh:/app/start-dev.sh:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []

  # Auth Service development configuration
  auth-service:
    build:
      context: ./services/auth-service
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
      - SECRET_KEY=dev-secret-key-change-in-production
      - AUTH_DB_PATH=/tmp/auth_dev.db
    volumes:
      # Mount source code for development
      - ./services/auth-service/src:/app/src:ro
      - ./services/auth-service/start-dev.sh:/app/start-dev.sh:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []

  # Network Service development configuration
  network-service:
    build:
      context: ./services/network
      target: development
    command: ["tini", "-s", "-g", "--", "./start-dev.sh"]
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT_MODE=true
      - WATCHFILES_FORCE_POLLING=1
    volumes:
      # Mount source code for development
      - ./services/network/src:/app/src:ro
      - ./services/network/config:/app/config:ro
      - ./services/network/start-dev.sh:/app/start-dev.sh:ro
    # Remove read-only constraints for development
    read_only: false
    tmpfs: []
