[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = [
    "test_auth.py",
    "test_auth_comprehensive.py"
]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short"
filterwarnings = [
    "ignore::DeprecationWarning:passlib.*",
    "ignore::DeprecationWarning:jose.*",
    "ignore::DeprecationWarning:pydantic.*",
    "ignore::DeprecationWarning:httpx.*",
    "ignore::DeprecationWarning:fastapi.*"
]