version: "3.8"

services:
  # API Gateway Service (Phase 3 Containerized)
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eunice-api-gateway
    ports:
      - "8001:8001"
    environment:
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8001

      # MCP Server Configuration
      - MCP_SERVER_HOST=mcp-server
      - MCP_SERVER_PORT=9000

      # Logging
      - LOG_LEVEL=INFO

      # CORS Configuration
      - CORS_ORIGINS=*

      # Health Check Configuration
      - HEALTH_CHECK_TIMEOUT=5
      - MCP_CONNECTION_RETRY_ATTEMPTS=3
      - MCP_CONNECTION_RETRY_DELAY=5

    depends_on:
      - mcp-server

    networks:
      - eunice-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    labels:
      - "com.eunice.service=api-gateway"
      - "com.eunice.version=3.0.0"
      - "com.eunice.phase=phase3"

  # MCP Server Service (existing from Phase 2)
  mcp-server:
    build:
      context: ../mcp-server
      dockerfile: Dockerfile
    container_name: eunice-mcp-server
    ports:
      - "9000:9000"
    environment:
      - LOG_LEVEL=INFO
      - PORT=9000
      - HOST=0.0.0.0

    networks:
      - eunice-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "python", "validate.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    labels:
      - "com.eunice.service=mcp-server"
      - "com.eunice.version=2.0.0"
      - "com.eunice.phase=phase2-enhanced"

  # Development Tools (optional)
  nginx:
    image: nginx:alpine
    container_name: eunice-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    networks:
      - eunice-network
    restart: unless-stopped
    profiles:
      - production

# Networks
networks:
  eunice-network:
    driver: bridge
    name: eunice-network
    labels:
      - "com.eunice.network=main"

# Volumes (for persistent data if needed)
volumes:
  api-gateway-logs:
    name: eunice-api-gateway-logs
    labels:
      - "com.eunice.volume=logs"
