version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: eunice-postgres
    environment:
      POSTGRES_DB: eunice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eunice"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eunice-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: eunice-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eunice-network

  # Database Service
  database-service:
    build: .
    container_name: eunice-database-service
    ports:
      - "8011:8011"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/eunice
      - REDIS_URL=redis://redis:6379
      - HOST=0.0.0.0
      - PORT=8011
      - LOG_LEVEL=INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8011/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - eunice-network

volumes:
  postgres_data:

networks:
  eunice-network:
    external: true
    name: mcp-server_eunice-network
