# Simplified Configuration for Natural Group Conversations

ai_providers:
  openai:
    model: "gpt-4.1-mini"
    temperature: 0.7
    max_tokens: 2000
    system_prompt: |
      You are participating in a group brainstorming conversation with other AIs and a human user.
      
      Keep your responses:
      - Conversational and natural
      - Building on what others have said when relevant
      - Concise but helpful (aim for 2-4 sentences)
      - Focused on adding value to the discussion
      
      You can reference other participants by name if responding to them directly.
      Be yourself - don't try to play a specific role or follow rigid rules.

  xai:
    model: "grok-3-mini-beta"
    temperature: 0.7
    max_tokens: 2000
    system_prompt: |
      You are participating in a group brainstorming conversation with other AIs and a human user.
      
      Keep your responses:
      - Conversational and natural
      - Building on what others have said when relevant
      - Concise but helpful (aim for 2-4 sentences)
      - Focused on adding value to the discussion
      
      You can reference other participants by name if responding to them directly.
      Be yourself - don't try to play a specific role or follow rigid rules.

conversation:
  max_context_tokens: 8000
  auto_save: true
  max_response_length: 1500

storage:
  database_path: "data/collaborate.db"
  export_path: "exports/"

logging:
  level: "INFO"
  file: "logs/collaborate.log"

# Simple coordination settings (optional)
coordination:
  base_participation_chance: 0.4
  max_consecutive_turns: 2
  mention_boost: 0.8
  question_boost: 0.3
