version: "3.8"

services:
  # Enhanced MCP Server (from Phase 3.1)
  mcp-server:
    build: ../mcp-server
    ports:
      - "9000:9000"
    environment:
      - MCP_HOST=0.0.0.0
      - MCP_PORT=9000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/eunice
      - REDIS_URL=redis://redis:6379 # Internal port stays same
      - LOG_LEVEL=INFO
      - ENABLE_METRICS=true
    depends_on:
      - postgres
      - redis
    networks:
      - eunice-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Literature Agent Service (Phase 3.2)
  literature-agent:
    build: .
    environment:
      - AGENT_ID=literature-agent-001
      - AGENT_TYPE=literature_search # Match MCP server allowed types
      - MCP_SERVER_URL=ws://mcp-server:9000
      - LOG_LEVEL=INFO
    depends_on:
      - mcp-server
    networks:
      - eunice-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Infrastructure Services
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=eunice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eunice-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379" # Use different external port to avoid conflict
    volumes:
      - redis_data:/data
    networks:
      - eunice-network
    command: redis-server --appendonly yes

networks:
  eunice-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
